##############################
#*** [[[ SPAMM CONFIG ]]] ***#
##############################

delay: 40
#The amount in server ticks Spamm will monitor for another consecutive chat message
#If you do not know what this does, leave it as it is
#20 TICKS = 1 SECOND

cooldown: 20
#The amount in server ticks Spamm uses to lower a player's spam count
#If you do not know what this does, leave it as it is
#20 TICKS = 1 SECOND

log: true
#If set to true, will create a spam log of everyone who has spammed
#File is called spamlog.txt

update: true
#If set to true, when a new Spamm version is released, it will automatically download it
#If not, it will notify you of a new version but do nothing
#Downloads can still be manually triggered via /spamm update

metrics: true
#If set to true, will send plugin stats to MCStats.org
#NOTE: This does not keep track of confidential information, only plugin-related info

count:
  warning: 3
  #How many times you can spam before being warned
  punishment: 7
  #How many times you can spam before being punished

punishments:
  kick: true
  #Kick the spammer
  ban: false
  #Ban em' if you hate em'

