name: Spamm
main: me.dmhacker.spamm.Spamm
version: 1.1.1
description: Prevents those darn client spammers!
author: skyrimfan1
load: POSTWORLD
commands:
  spamm:
    description: The generic Spamm command
permissions:
  spamm.exempt:
    description: Allows a user to bypass Spamm
    default: op
  spamm.update:
    description: Allows an admin (or player) to update Spamm
    default: op


  